<?php

namespace Drupal\breezy_layouts\Element;

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element\FormElement;

/**
 * Provides a form element for managing BreezyLayouts element options.
 *
 * @FormElement("breezy_layouts_element_options")
 */
class BreezyLayoutsElementOptions extends FormElement {

  /**
   * {@inheritdoc}
   */
  public function getInfo() {
    $class = get_class();
    return [
      '#input' => TRUE,
      '#process' => [
        [$class, 'processBreezyElementOptions'],
        [$class, 'processAjaxForm'],
      ],
      '#theme_wrapper' => ['form_element'],
      '#options_description' => FALSE,
    ];
  }

  /**
   * {@inheritdoc}
   */
  public static function valueCallback(&$element, $input, FormStateInterface $form_state) {
    if ($input === FALSE) {
      if (isset($element['#default_value'])) {
        return $element['#default_value'];
      }
      else {
        return [];
      }
    }
    return parent::valueCallback($element, $input, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public static function processBreezyElementOptions(&$element, FormStateInterface $form_state, &$complete_form) {
    $element['#tree'] = TRUE;

    $properties = ['#label', '#labels', '#min_items', '#empty_items', '#add_more_items'];

    // @todo Multiple options.
    $element['options'] = [];
  }

}
